# Generated by Django 2.1.4 on 2019-01-07 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oldboy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='课程')),
                ('summary', models.CharField(max_length=150, verbose_name='简介')),
                ('detail', models.CharField(max_length=1000, verbose_name='详细')),
                ('img', models.FileField(upload_to='static/img/course', verbose_name='课程图片')),
                ('target', models.URLField(verbose_name='跳转路径')),
                ('status', models.IntegerField(choices=[(1, '上线'), (2, '下线')], verbose_name='状态')),
                ('weight', models.IntegerField(verbose_name='权重')),
            ],
            options={
                'verbose_name_plural': '公告表',
            },
        ),
        migrations.AlterModelOptions(
            name='slideshow',
            options={'verbose_name_plural': '轮播图表'},
        ),
        migrations.AlterField(
            model_name='slideshow',
            name='img',
            field=models.FileField(upload_to='static/img/sliders', verbose_name='图片路径'),
        ),
    ]
