# Generated by Django 2.1.4 on 2019-01-07 04:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('oldboy', '0002_auto_20190107_1052'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name_plural': '课程表'},
        ),
        migrations.RemoveField(
            model_name='course',
            name='target',
        ),
        migrations.AddField(
            model_name='slideshow',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='img',
            field=models.ImageField(upload_to='static/img/course', verbose_name='课程图片'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=32, unique=True, verbose_name='课程'),
        ),
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.IntegerField(choices=[(1, '上线'), (2, '下线')], default=1, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='slideshow',
            name='img',
            field=models.ImageField(upload_to='static/img/sliders', verbose_name='图片路径'),
        ),
        migrations.AlterField(
            model_name='slideshow',
            name='name',
            field=models.CharField(max_length=32, unique=True, verbose_name='图片名称'),
        ),
        migrations.AlterField(
            model_name='slideshow',
            name='status',
            field=models.IntegerField(choices=[(1, '上线'), (2, '下线')], default=1, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='slideshow',
            name='target',
            field=models.CharField(max_length=256, verbose_name='跳转路径'),
        ),
    ]
