# Generated by Django 2.1.4 on 2019-01-07 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oldboy', '0004_auto_20190107_1244'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name_plural': '课程'},
        ),
        migrations.AlterModelOptions(
            name='slideshow',
            options={'verbose_name_plural': '轮播图'},
        ),
        migrations.AddField(
            model_name='video',
            name='detail',
            field=models.CharField(default=None, max_length=1000, verbose_name='详细'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='img',
            field=models.ImageField(default=0, upload_to='static/img/course', verbose_name='视频图片'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='summary',
            field=models.CharField(default=0, max_length=150, verbose_name='简介'),
            preserve_default=False,
        ),
    ]
