# Generated by Django 2.1.4 on 2019-01-07 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oldboy', '0005_auto_20190107_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.IntegerField(choices=[(1, '上线'), (2, '下线')], default=1, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='video',
            name='status',
            field=models.IntegerField(choices=[(1, '上线'), (2, '下线')], default=1, verbose_name='状态'),
        ),
    ]
