# Generated by Django 2.1.4 on 2019-03-04 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oldboy', '0007_remove_course_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='LetterOfThanks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='标题')),
                ('content', models.TextField(max_length=5000, verbose_name='内容')),
            ],
            options={
                'verbose_name_plural': '学生感谢信',
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='标题')),
                ('summary', models.CharField(max_length=150, verbose_name='简介')),
                ('detail', models.TextField(max_length=1000, verbose_name='详细')),
                ('weight', models.IntegerField(default=0, verbose_name='权重')),
                ('status', models.IntegerField(choices=[(1, '上线'), (2, '下线')], default=1, verbose_name='状态')),
            ],
            options={
                'verbose_name_plural': '最新公告',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('company', models.CharField(max_length=64, verbose_name='就业单位')),
                ('salary', models.CharField(max_length=32, verbose_name='薪资')),
                ('weight', models.IntegerField(default=0, verbose_name='权重')),
                ('status', models.IntegerField(choices=[(1, '上线'), (2, '下线')], default=1, verbose_name='状态')),
                ('letter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='oldboy.LetterOfThanks')),
            ],
            options={
                'verbose_name_plural': '学生信息',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('age', models.CharField(max_length=20, verbose_name='年龄')),
                ('weight', models.IntegerField(default=0, verbose_name='权重')),
                ('status', models.IntegerField(choices=[(1, '上线'), (2, '下线')], default=1, verbose_name='状态')),
            ],
            options={
                'verbose_name_plural': '老师信息',
            },
        ),
        migrations.AlterField(
            model_name='course',
            name='img',
            field=models.ImageField(upload_to='static/img/course', verbose_name='图片路径'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='course',
            field=models.ManyToManyField(related_name='th', to='oldboy.Course', verbose_name='负责课程'),
        ),
    ]
