# Generated by Django 2.1.4 on 2019-03-04 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oldboy', '0008_auto_20190304_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='letter',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oldboy.LetterOfThanks'),
        ),
    ]
