# Generated by Django 2.1.4 on 2019-03-04 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oldboy', '0009_auto_20190304_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='summary',
            field=models.CharField(default=1, max_length=150, verbose_name='简介'),
            preserve_default=False,
        ),
    ]
