# Generated by Django 2.1.4 on 2019-03-04 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oldboy', '0010_teacher_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='summary',
            field=models.CharField(max_length=300, verbose_name='简介'),
        ),
    ]
