# Generated by Django 2.1.4 on 2019-03-04 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oldboy', '0011_auto_20190304_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/students', verbose_name='图片路径'),
        ),
    ]
